services:
  - type: web
    name: phytovaria-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./phytovaria.db
      - key: ALLOW_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
